---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vovoco5/public_html/rnzsoftwareds.com
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -av --delete --exclude=".git" --exclude=".github" --exclude=".gitignore" --exclude=".cpanel.yml" ./ $DEPLOYPATH/
